### ISSUE TITLE
PHP version bump

### ISSUE THREAD

**Issue by weeirishman** [genesis/wordpress#153]
@EvanK - any chance we could get the PHP version bumped to `>= 5.4`?

**Comment by EvanK** [comment]
This is tricky because we're using Ubuntu's stock apache/php packages, and genesis is still based on Precise (12.04).

So...we'd have to find ppa's for precise that backport not only PHP 5.4+, but any php extensions in use (including mysql, curl, gd), and _possibly_ the php apache module (I'd have to investigate further if that's the case).

It might be simpler (**and I'd highly recommend**) to [import the existing genesis site into evolution](https://github.com/evolution/wordpress/blob/master/docs/TUTORIAL-IMPORT.md), which is based on Trusty (14.04) and comes with stock php 5.5 and apache 2.4

**Comment by weeirishman** [comment]
Yeah an import to Evolution makes most sense then.  Thanks.
